Repository googleapis/java-analytics-data, pull requests merged in 2020-08, with the labels that each got.

#7 chore: fix cloud name usage
  google-analytics-data-bom/pom.xml
  grpc-google-analytics-data-v1alpha/pom.xml
  pom.xml
  proto-google-analytics-data-v1alpha/pom.xml
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes

#9 build: switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#10 chore: fix version replace tag
  google-analytics-data-bom/pom.xml
Labels: cla: yes

#13 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none
