Repository googleapis/java-analytics-data, pull requests merged in 2021-09, with the labels that each got.

#329 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: analyticsdata

#336 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: automerge, cla: yes, api: analyticsdata

#346 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: analyticsdata
