Repository googleapis/java-analytics-data, pull requests merged in 2021-02, with the labels that each got.

#130 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, context: partial

#131 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#133 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#134 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#135 docs: generate sample code in the Java microgenerator
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/AlphaAnalyticsDataClient.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/package-info.java
  synth.metadata
Labels: automerge, cla: yes, context: full, samples

#137 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#140 chore: switch to using pre-generated library
  synth.py
Labels: automerge, cla: yes

#141 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#154 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/gapic_metadata.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#161 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
