Repository googleapis/java-analytics-data, pull requests merged in 2021-03, with the labels that each got.

#163 feat(generator): update protoc to v3.15.3
  proto-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/DimensionValue.java
  proto-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/DimensionValueOrBuilder.java
  proto-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/Filter.java
  proto-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/FilterOrBuilder.java
  proto-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/MetricValue.java
  proto-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/MetricValueOrBuilder.java
  proto-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/NumericValue.java
  proto-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/NumericValueOrBuilder.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/DimensionValue.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/DimensionValueOrBuilder.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/MetricValue.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/MetricValueOrBuilder.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/NumericValue.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/NumericValueOrBuilder.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#166 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#167 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#168 chore(release): update Java microgenerator to 1.0.1
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/AlphaAnalyticsDataClient.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/AlphaAnalyticsDataSettings.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/package-info.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/stub/AlphaAnalyticsDataStub.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/stub/AlphaAnalyticsDataStubSettings.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/stub/GrpcAlphaAnalyticsDataCallableFactory.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1alpha/stub/GrpcAlphaAnalyticsDataStub.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/BetaAnalyticsDataClient.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/BetaAnalyticsDataSettings.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/package-info.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/stub/BetaAnalyticsDataStub.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/stub/BetaAnalyticsDataStubSettings.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/stub/GrpcBetaAnalyticsDataCallableFactory.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/stub/GrpcBetaAnalyticsDataStub.java
  google-analytics-data/src/test/java/com/google/analytics/data/v1alpha/AlphaAnalyticsDataClientTest.java
  google-analytics-data/src/test/java/com/google/analytics/data/v1alpha/MockAlphaAnalyticsData.java
  google-analytics-data/src/test/java/com/google/analytics/data/v1alpha/MockAlphaAnalyticsDataImpl.java
  google-analytics-data/src/test/java/com/google/analytics/data/v1beta/BetaAnalyticsDataClientTest.java
  google-analytics-data/src/test/java/com/google/analytics/data/v1beta/MockBetaAnalyticsData.java
  google-analytics-data/src/test/java/com/google/analytics/data/v1beta/MockBetaAnalyticsDataImpl.java
  proto-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/MetadataName.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/MetadataName.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#169 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#170 fix!: rename the 'page_size', 'page_token', 'total_size' fields to 'limit', 'offset' and 'row_count' respectively
  google-analytics-data/clirr-ignored-differences.xml
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/BetaAnalyticsDataClient.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/BetaAnalyticsDataSettings.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/gapic_metadata.json
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/package-info.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/stub/BetaAnalyticsDataStub.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/stub/BetaAnalyticsDataStubSettings.java
  google-analytics-data/src/main/java/com/google/analytics/data/v1beta/stub/GrpcBetaAnalyticsDataStub.java
  google-analytics-data/src/test/java/com/google/analytics/data/v1beta/BetaAnalyticsDataClientTest.java
  proto-google-analytics-data-v1beta/clirr-ignored-differences.xml
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/AnalyticsDataApiProto.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/RunRealtimeReportRequest.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/RunRealtimeReportRequestOrBuilder.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/RunRealtimeReportResponse.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/RunRealtimeReportResponseOrBuilder.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/RunReportRequest.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/RunReportRequestOrBuilder.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/RunReportResponse.java
  proto-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/RunReportResponseOrBuilder.java
  proto-google-analytics-data-v1beta/src/main/proto/google/analytics/data/v1beta/analytics_data_api.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#173 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#172 chore: update gax-java dependency to 1.62
  grpc-google-analytics-data-v1alpha/src/main/java/com/google/analytics/data/v1alpha/AlphaAnalyticsDataGrpc.java
  grpc-google-analytics-data-v1beta/src/main/java/com/google/analytics/data/v1beta/BetaAnalyticsDataGrpc.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#174 chore: update java microgenerator to 1.0.2 Adds request initialization to sample code
  google-analytics-data/src/test/java/com/google/analytics/data/v1alpha/MockAlphaAnalyticsDataImpl.java
  google-analytics-data/src/test/java/com/google/analytics/data/v1beta/MockBetaAnalyticsDataImpl.java
  synth.metadata
Labels: cla: yes, context: full, samples

#177 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#179 chore: add analytics-dpe as codeowner
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
  .repo-metadata.json
Labels: automerge, cla: yes

#180 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#181 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
