Repository googleapis/java-analytics-data, pull requests merged in 2021-07, with the labels that each got.

#220 chore: release gapic-generator-java v1.0.10
  google-analytics-data/src/test/java/com/google/analytics/data/v1alpha/AlphaAnalyticsDataClientTest.java
  google-analytics-data/src/test/java/com/google/analytics/data/v1beta/BetaAnalyticsDataClientTest.java
  synth.metadata
Labels: api: analyticsdata, automerge, cla: yes, context: full

#230 chore: remove distributionManagement section
  pom.xml
Labels: api: analyticsdata, automerge, cla: yes

#231 chore: remove distributionManagement section
  google-analytics-data-bom/pom.xml
Labels: api: analyticsdata, automerge, cla: yes

#236 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: api: analyticsdata, automerge, cla: yes

#244 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#245 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#246 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#247 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#248 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#249 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#250 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#251 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#252 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#253 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#254 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#255 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#256 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#257 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#258 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#259 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#260 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#261 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#262 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#263 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#264 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#265 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#266 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#267 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#268 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#269 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#270 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#271 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#272 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#273 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#274 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#275 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, cla: yes

#276 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#277 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#278 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#279 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#280 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#281 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#282 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#283 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#285 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#286 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#287 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#288 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#289 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#290 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#291 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#292 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: analyticsdata, automerge, cla: yes

#295 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: analyticsdata, automerge, cla: yes

#296 feat: configure initial sp version
  README.md
Labels: api: analyticsdata, automerge, cla: yes
